### ISSUE TITLE
Check el (Ελληνικά) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#172]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 172_el_locale
- Commit and create PR

**Comment by ManosPapaioannou** [comment]
Hello, I am a native greek speaker so i can probably help out with this issue but this is my first time I do it so I don't know how to start!
