### ISSUE TITLE
Check es (Español) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#173]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 173_es_locale
- Commit and create PR

**Comment by LautaroLobo12** [comment]
Hey, good project! I'm a Native Spanish speaker and a Ruby-newbie, I'll do my best to find and fix any typos that I may encounter :+1: 

I'll run it on locale, give it a read, and use a spell checker.

**Comment by khusnetdinov** [comment]
@LautaroLobo12 Thanks!

**Comment by krthr** [comment]
Hey! I'm a native spanish speaker too... I'm working on it. Thank you.
