### ISSUE TITLE
Check it (Italiano) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#177]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 177_it_locale
- Commit and create PR

**Comment by tsrandrei** [comment]
@khusnetdinov I pick this

**Comment by spassaro80** [comment]
Hello, can I pick this one? Thks

**Comment by khusnetdinov** [comment]
@spassaro80 Sure

**Comment by augustozanellato** [comment]
Any progress @spassaro80?

**Comment by spassaro80** [comment]
Not yet. Feel free to pick it up if you want to.

**Comment by augustozanellato** [comment]
I'm picking up this issue, I'll probably be sending a PR in ~24 hours
