### ISSUE TITLE
Check ko (한국어) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#179]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 179_ko_locale
- Commit and create PR

**Comment by khusnetdinov** [comment]
Can somebody help?
@junegunn, @buo, @kciter, @devxoul, @keepcosmos, @mu29, @rorlakr, @benjaminkim, @luciuschoi, @ssut, @shaynekang, @hatemogi, @meinside, @nacyot, @kimsuelim, @baxang, @aproxacs, @nerdyfactory, @rorlab, @cycorld, @riseshia, @anamba, @sangdol, @jongha

**Comment by abu899** [comment]
Hello. I'd like to fix typos. Can I join this?

**Comment by mkhusnetdinov** [comment]
@abu899 Sure! Thanks

**Comment by khusnetdinov** [comment]
@abu899 Sure. PR Welcome.
