### ISSUE TITLE
Check pt (Português) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#182]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 182_pt_locale
- Commit and create PR

**Comment by khusnetdinov** [comment]
Can somebody help?
@cesarferreira, @methodmissing, @goncalossilva, @filp, @kvokka, @etewiah, @rubenfonseca, @dmfrancisco, @bearstouch, @r00t-3xp10it, @joaquimserafim, @rfelix, @nelsonsilva, @webcracy, @rtfpessoa, @rikas, @tdantas, @subvisual, @whitesmith, @mindera, @josemotanet, @zamith, @imaginary-cloud, @manybots, @pedrocarrico

**Comment by rikas** [comment]
@khusnetdinov I can help, just tell me what's the process...

**Comment by khusnetdinov** [comment]
@rikas There is i18n folder with pt.yml file that contains locales. It would be great if you check it and fix typos. I transaled via auto transaltor and I see that here are typos.

**Comment by khusnetdinov** [comment]
@rikas Update issue description

**Comment by rikas** [comment]
@khusnetdinov I'm Portuguese (from Portugal — usually just `pt` or `pt_PT`) but the most common spoken Portuguese is from Brazil (they are way more than us — `pt_BR`). I can correct the `pt` one but it will be in fact a `pt_PT` translation.

With this said, can we have a specific translation for each "version" of Portuguese? Because they will differ (think about `en_US` and `en_UK` but with even more differences).

**Comment by khusnetdinov** [comment]
@rikas Well, lets start from `pt_PT` if I find somebody who can help with `pt_BR` I will create one more locale

**Comment by ialvarenga** [comment]
I see that you're looking for someone who can help with pt_BR translation. Well, here I am!

**Comment by ialvarenga** [comment]
I see that you're looking for someone who can help with the `pt_BR` translation. Well, here I am!

**Comment by barbaraips** [comment]
Hello, do you still need help with the `pt_br` translation? I can take care of that.
