### ISSUE TITLE
Check ro (Română) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#183]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 183_ro_locale
- Commit and create PR

**Comment by khusnetdinov** [comment]
Can somebody help?
@alexandru, @jassa, @vitalie, @icebreaker, @ihoka, @viseztrance, @mess110, @courseware, @janosrusiczki, @kitsched, @talek, @bogdanrada, @thegengen, @gtarnovan, @cubus, @minciue, @cristianbica, @revolter, @andreimaxim, @shuriu, @madalinoprea, @mixandgo, @pickaxe-club, @maria

**Comment by janosrusiczki** [comment]
I can help with some Romanian typos, but I'm not very sure that there are that many Romanian developers who will want to read the page in Romanian. We're quite used to reading documentation in English.

Anyway, I'll open a PR as my time permits.
