### ISSUE TITLE
Check vi (Tiếng Việt) locale and fix typos

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/betterdocs#188]
Check locales by native and fix typos.

Project use [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). Each locale file are keeped in `_18n` folder.
For example `en` is located in `_18n/en.yml` file.

Project was translated by translation service not by human. So it can keep typos.

Need to check current issue language.

- Fork
- Create branch 188_vi_locale
- Commit and create PR

**Comment by khusnetdinov** [comment]
Can somebody help ?
@fongfan999, @tumf, @nguyenanh, @giangnguyennet, @tranvictor, @tienle, @starchow, @vinhnglx, @vantran, @cqbinh, @phuongnd08, @thetrung, @huyngvu, @ntamvl,  @nguyenquangminh0711, @tpdorsey, @minhnghivn, @quanghoan, @kimquy

**Comment by phuongnd08** [comment]
I checked the locale, there are various translation that can be improved. I don't have much spare time these days but already passed this to a few friends.

**Comment by khusnetdinov** [comment]
@phuongnd08 Thanks!
